nodejs:
  applicationPort: 3000
  aadIdentityName: prl
  ingressHost: prl-citizen-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/prl/citizen-frontend:latest'
  #  Uncomment once the vault containing the app insights key has been set up
  #  keyVaults:
  #    prl:
  #      secrets:
  #        - AppInsightsInstrumentationKey
  environment:
  keyVaults:
    prl:
      resourceGroup: prl
      secrets:
        - AppInsightsInstrumentationKey
